/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.tables;

import java.awt.*;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;

/**
 * @author ahmad
 */
public class Hotel_Mangment extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_Mangment
     */
    public Hotel_Mangment() {
        initComponents();
    }
    tables t = new tables();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HotelPanel = new javax.swing.JPanel();
        instertHotel2 = new javax.swing.JButton();
        hotelLocInsert1 = new javax.swing.JLabel();
        locHotelInsert1 = new javax.swing.JTextField();
        HotelIDInsert1 = new javax.swing.JLabel();
        insertHotelID1 = new javax.swing.JTextField();
        HotelNameInsert1 = new javax.swing.JLabel();
        insertHotelName1 = new javax.swing.JTextField();
        updateHotel1 = new javax.swing.JButton();
        removeHotel1 = new javax.swing.JButton();
        displayHotel = new javax.swing.JButton();
        RoomPanel = new javax.swing.JPanel();
        removeRoom = new javax.swing.JButton();
        insertRoom = new javax.swing.JButton();
        updateRoom = new javax.swing.JButton();
        roomPrice = new javax.swing.JTextField();
        HotelNameInsert3 = new javax.swing.JLabel();
        RoomNumber = new javax.swing.JTextField();
        HotelIDInsert3 = new javax.swing.JLabel();
        roomType = new javax.swing.JTextField();
        hotelLocInsert3 = new javax.swing.JLabel();
        HotelIDInsert5 = new javax.swing.JLabel();
        roomHotelId = new javax.swing.JTextField();
        displayRoom = new javax.swing.JButton();
        EmployeePanel = new javax.swing.JPanel();
        removeEmployee = new javax.swing.JButton();
        updateEmployee = new javax.swing.JButton();
        insertEmployee = new javax.swing.JButton();
        EmpIDinsert = new javax.swing.JLabel();
        empID = new javax.swing.JTextField();
        EmpNameinsert = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        EmpSalaryInsert = new javax.swing.JLabel();
        empSalary = new javax.swing.JTextField();
        EmpIDinsert1 = new javax.swing.JLabel();
        empHotelID = new javax.swing.JTextField();
        displayRoom1 = new javax.swing.JButton();
        CustomerPanel = new javax.swing.JPanel();
        removeCustomer = new javax.swing.JButton();
        updateCustomer = new javax.swing.JButton();
        insertCustomer = new javax.swing.JButton();
        CIDinsert = new javax.swing.JLabel();
        customerID = new javax.swing.JTextField();
        CNameinsert = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        CusRoomNumber = new javax.swing.JTextField();
        roomnumberinsert = new javax.swing.JLabel();
        displayCus = new javax.swing.JButton();
        RolePanel = new javax.swing.JPanel();
        removeRole = new javax.swing.JButton();
        updateRole = new javax.swing.JButton();
        insertRole = new javax.swing.JButton();
        roleNameinsert = new javax.swing.JLabel();
        roleName = new javax.swing.JTextField();
        roleRankinsert = new javax.swing.JLabel();
        roleRank = new javax.swing.JTextField();
        displayRole = new javax.swing.JButton();
        Workpanel = new javax.swing.JPanel();
        removeWork = new javax.swing.JButton();
        updateWork = new javax.swing.JButton();
        insertWork = new javax.swing.JButton();
        roleNameinsert1 = new javax.swing.JLabel();
        workEmpID = new javax.swing.JTextField();
        roleRankinsert1 = new javax.swing.JLabel();
        workRoleName = new javax.swing.JTextField();
        displayWork = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(53, 205, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(53, 205, 153));
        jPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel1formAncestorResized(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(32, 33, 55));

        HotelPanel.setBackground(new java.awt.Color(32, 33, 55));
        HotelPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HotelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instertHotel2.setBackground(new java.awt.Color(53, 205, 153));
        instertHotel2.setText("insert");
        instertHotel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        instertHotel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instertHotel2ActionPerformed(evt);
            }
        });
        HotelPanel.add(instertHotel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 40));

        hotelLocInsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hotelLocInsert1.setForeground(new java.awt.Color(240, 240, 240));
        hotelLocInsert1.setText("location");
        HotelPanel.add(hotelLocInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 20));

        locHotelInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locHotelInsert1ActionPerformed(evt);
            }
        });
        HotelPanel.add(locHotelInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 250, -1));

        HotelIDInsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotelIDInsert1.setForeground(new java.awt.Color(240, 240, 240));
        HotelIDInsert1.setText("ID");
        HotelPanel.add(HotelIDInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        insertHotelID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertHotelID1ActionPerformed(evt);
            }
        });
        HotelPanel.add(insertHotelID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, -1));

        HotelNameInsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotelNameInsert1.setForeground(new java.awt.Color(240, 240, 240));
        HotelNameInsert1.setText("name");
        HotelPanel.add(HotelNameInsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, 20));

        insertHotelName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertHotelName1ActionPerformed(evt);
            }
        });
        HotelPanel.add(insertHotelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 240, -1));

        updateHotel1.setBackground(new java.awt.Color(53, 205, 153));
        updateHotel1.setText("update");
        updateHotel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHotel1ActionPerformed(evt);
            }
        });
        HotelPanel.add(updateHotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 160, 40));

        removeHotel1.setBackground(new java.awt.Color(53, 205, 153));
        removeHotel1.setText("remove");
        removeHotel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeHotel1ActionPerformed(evt);
            }
        });
        HotelPanel.add(removeHotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 160, 40));

        displayHotel.setBackground(new java.awt.Color(53, 205, 153));
        displayHotel.setText("display");
        displayHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayHotelActionPerformed(evt);
            }
        });
        HotelPanel.add(displayHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 160, 40));

        jTabbedPane1.addTab("Hotel", HotelPanel);

        RoomPanel.setBackground(new java.awt.Color(32, 33, 55));
        RoomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeRoom.setBackground(new java.awt.Color(53, 205, 153));
        removeRoom.setText("remove");
        removeRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRoomActionPerformed(evt);
            }
        });
        RoomPanel.add(removeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 160, 40));

        insertRoom.setBackground(new java.awt.Color(53, 205, 153));
        insertRoom.setText("insert");
        insertRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRoomActionPerformed(evt);
            }
        });
        RoomPanel.add(insertRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 40));

        updateRoom.setBackground(new java.awt.Color(53, 205, 153));
        updateRoom.setText("update");
        updateRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoomActionPerformed(evt);
            }
        });
        RoomPanel.add(updateRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 160, 40));

        roomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomPriceActionPerformed(evt);
            }
        });
        RoomPanel.add(roomPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 220, -1));

        HotelNameInsert3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotelNameInsert3.setForeground(new java.awt.Color(240, 240, 240));
        HotelNameInsert3.setText("price");
        RoomPanel.add(HotelNameInsert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 20));

        RoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumberActionPerformed(evt);
            }
        });
        RoomPanel.add(RoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        HotelIDInsert3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotelIDInsert3.setForeground(new java.awt.Color(240, 240, 240));
        HotelIDInsert3.setText("number");
        RoomPanel.add(HotelIDInsert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        roomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeActionPerformed(evt);
            }
        });
        RoomPanel.add(roomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 240, -1));

        hotelLocInsert3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hotelLocInsert3.setForeground(new java.awt.Color(240, 240, 240));
        hotelLocInsert3.setText("type");
        RoomPanel.add(hotelLocInsert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, 20));

        HotelIDInsert5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HotelIDInsert5.setForeground(new java.awt.Color(240, 240, 240));
        HotelIDInsert5.setText("hotel ID");
        RoomPanel.add(HotelIDInsert5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, 20));

        roomHotelId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomHotelIdActionPerformed(evt);
            }
        });
        RoomPanel.add(roomHotelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 160, -1));

        displayRoom.setBackground(new java.awt.Color(53, 205, 153));
        displayRoom.setText("display");
        displayRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRoomActionPerformed(evt);
            }
        });
        RoomPanel.add(displayRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 160, 40));

        jTabbedPane1.addTab("Room", RoomPanel);

        EmployeePanel.setBackground(new java.awt.Color(32, 33, 55));
        EmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeEmployee.setBackground(new java.awt.Color(53, 205, 153));
        removeEmployee.setText("remove");
        removeEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeActionPerformed(evt);
            }
        });
        EmployeePanel.add(removeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 160, 40));

        updateEmployee.setBackground(new java.awt.Color(53, 205, 153));
        updateEmployee.setText("update");
        updateEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeActionPerformed(evt);
            }
        });
        EmployeePanel.add(updateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 160, 40));

        insertEmployee.setBackground(new java.awt.Color(53, 205, 153));
        insertEmployee.setText("insert");
        insertEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertEmployeeActionPerformed(evt);
            }
        });
        EmployeePanel.add(insertEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 160, 40));

        EmpIDinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIDinsert.setForeground(new java.awt.Color(240, 240, 240));
        EmpIDinsert.setText("ID");
        EmployeePanel.add(EmpIDinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 20));

        empID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDActionPerformed(evt);
            }
        });
        EmployeePanel.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 70, -1));

        EmpNameinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpNameinsert.setForeground(new java.awt.Color(240, 240, 240));
        EmpNameinsert.setText("name");
        EmployeePanel.add(EmpNameinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 20));

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });
        EmployeePanel.add(empName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 240, -1));

        EmpSalaryInsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpSalaryInsert.setForeground(new java.awt.Color(240, 240, 240));
        EmpSalaryInsert.setText("salary");
        EmployeePanel.add(EmpSalaryInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        empSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSalaryActionPerformed(evt);
            }
        });
        EmployeePanel.add(empSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 250, -1));

        EmpIDinsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmpIDinsert1.setForeground(new java.awt.Color(240, 240, 240));
        EmpIDinsert1.setText("hotel ID");
        EmployeePanel.add(EmpIDinsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 20));

        empHotelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empHotelIDActionPerformed(evt);
            }
        });
        EmployeePanel.add(empHotelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 100, -1));

        displayRoom1.setBackground(new java.awt.Color(53, 205, 153));
        displayRoom1.setText("display");
        displayRoom1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRoom1ActionPerformed(evt);
            }
        });
        EmployeePanel.add(displayRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 160, 40));

        jTabbedPane1.addTab("Employee", EmployeePanel);

        CustomerPanel.setBackground(new java.awt.Color(32, 33, 55));
        CustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeCustomer.setBackground(new java.awt.Color(53, 205, 153));
        removeCustomer.setText("remove");
        removeCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerActionPerformed(evt);
            }
        });
        CustomerPanel.add(removeCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 160, 40));

        updateCustomer.setBackground(new java.awt.Color(53, 205, 153));
        updateCustomer.setText("update");
        updateCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerActionPerformed(evt);
            }
        });
        CustomerPanel.add(updateCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 160, 40));

        insertCustomer.setBackground(new java.awt.Color(53, 205, 153));
        insertCustomer.setText("insert");
        insertCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCustomerActionPerformed(evt);
            }
        });
        CustomerPanel.add(insertCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 160, 40));

        CIDinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CIDinsert.setForeground(new java.awt.Color(240, 240, 240));
        CIDinsert.setText("ID");
        CustomerPanel.add(CIDinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIDActionPerformed(evt);
            }
        });
        CustomerPanel.add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        CNameinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CNameinsert.setForeground(new java.awt.Color(240, 240, 240));
        CNameinsert.setText("name");
        CustomerPanel.add(CNameinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, 20));

        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });
        CustomerPanel.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, -1));

        CusRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusRoomNumberActionPerformed(evt);
            }
        });
        CustomerPanel.add(CusRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 210, -1));

        roomnumberinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomnumberinsert.setForeground(new java.awt.Color(240, 240, 240));
        roomnumberinsert.setText("room number");
        CustomerPanel.add(roomnumberinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, 20));

        displayCus.setBackground(new java.awt.Color(53, 205, 153));
        displayCus.setText("display");
        displayCus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCusActionPerformed(evt);
            }
        });
        CustomerPanel.add(displayCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 160, 40));

        jTabbedPane1.addTab("Customer", CustomerPanel);

        RolePanel.setBackground(new java.awt.Color(32, 33, 55));
        RolePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeRole.setBackground(new java.awt.Color(53, 205, 153));
        removeRole.setText("remove");
        removeRole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRoleActionPerformed(evt);
            }
        });
        RolePanel.add(removeRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 160, 40));

        updateRole.setBackground(new java.awt.Color(53, 205, 153));
        updateRole.setText("update");
        updateRole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRoleActionPerformed(evt);
            }
        });
        RolePanel.add(updateRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, 40));

        insertRole.setBackground(new java.awt.Color(53, 205, 153));
        insertRole.setText("insert");
        insertRole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertRoleActionPerformed(evt);
            }
        });
        RolePanel.add(insertRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 160, 40));

        roleNameinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roleNameinsert.setForeground(new java.awt.Color(240, 240, 240));
        roleNameinsert.setText("name");
        RolePanel.add(roleNameinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 20));

        roleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleNameActionPerformed(evt);
            }
        });
        RolePanel.add(roleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 230, -1));

        roleRankinsert.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roleRankinsert.setForeground(new java.awt.Color(240, 240, 240));
        roleRankinsert.setText("rank");
        RolePanel.add(roleRankinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, 20));

        roleRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleRankActionPerformed(evt);
            }
        });
        RolePanel.add(roleRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 240, -1));

        displayRole.setBackground(new java.awt.Color(53, 205, 153));
        displayRole.setText("display");
        displayRole.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRoleActionPerformed(evt);
            }
        });
        RolePanel.add(displayRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 160, 40));

        jTabbedPane1.addTab("Role", RolePanel);

        Workpanel.setBackground(new java.awt.Color(32, 33, 55));
        Workpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeWork.setBackground(new java.awt.Color(53, 205, 153));
        removeWork.setText("remove");
        removeWork.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        removeWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWorkActionPerformed(evt);
            }
        });
        Workpanel.add(removeWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 160, 40));

        updateWork.setBackground(new java.awt.Color(53, 205, 153));
        updateWork.setText("update");
        updateWork.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        updateWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWorkActionPerformed(evt);
            }
        });
        Workpanel.add(updateWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 160, 40));

        insertWork.setBackground(new java.awt.Color(53, 205, 153));
        insertWork.setText("insert");
        insertWork.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        insertWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertWorkActionPerformed(evt);
            }
        });
        Workpanel.add(insertWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 160, 40));

        roleNameinsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roleNameinsert1.setForeground(new java.awt.Color(240, 240, 240));
        roleNameinsert1.setText("Employee ID");
        Workpanel.add(roleNameinsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 20));

        workEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workEmpIDActionPerformed(evt);
            }
        });
        Workpanel.add(workEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, -1));

        roleRankinsert1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roleRankinsert1.setForeground(new java.awt.Color(240, 240, 240));
        roleRankinsert1.setText("Role name");
        Workpanel.add(roleRankinsert1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 20));

        workRoleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workRoleNameActionPerformed(evt);
            }
        });
        Workpanel.add(workRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 240, -1));

        displayWork.setBackground(new java.awt.Color(53, 205, 153));
        displayWork.setText("display");
        displayWork.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        displayWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayWorkActionPerformed(evt);
            }
        });
        Workpanel.add(displayWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 160, 40));

        jTabbedPane1.addTab("work AS", Workpanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1formAncestorResized
    }//GEN-LAST:event_jPanel1formAncestorResized

    private void insertRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRoleActionPerformed
        var name = roleName.getText();
        var rank = roleRank.getText();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
            System.out.println("connection done");
            PreparedStatement p = c.prepareStatement("INSERT INTO `role`(`name`, `rank`) VALUES (?,?)");
            p.setString(1, name);
            p.setString(2, rank);
            p.execute();
            c.close();
            System.out.println("insert done");
        } catch (SQLException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_insertRoleActionPerformed

    private void updateRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoleActionPerformed

        var name = roleName.getText();
        var rank = roleRank.getText();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
            System.out.println("connection done");
            PreparedStatement p = c.prepareStatement("UPDATE `role` SET `rank` = ? WHERE `role`.`name` = ?");
            p.setString(1, rank);
            p.setString(2, name);
            p.execute();
            c.close();
            System.out.println("update done");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateRoleActionPerformed

    private void removeRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRoleActionPerformed
        var name = roleName.getText();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
            System.out.println("connection done");
            PreparedStatement p = c.prepareStatement("DELETE FROM `role` WHERE `role`.`name` = ?");
            p.setString(1, name);
            p.execute();
            c.close();
            System.out.println("remove done");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_removeRoleActionPerformed

    private void insertCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCustomerActionPerformed
        var id = customerID.getText();
        var name = customerName.getText();
        var roomID = CusRoomNumber.getText();
        if (id.length() != 0) {
            int ID;
            int RoomNumber;
            try {
                ID = Integer.parseInt(id);
                RoomNumber = Integer.parseInt(roomID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("INSERT INTO `customer`(`ID`, `name`,`roomNumber`) VALUES (?,?,?)");
                p.setInt(1, ID);
                p.setString(2, name);
                p.setInt(3, RoomNumber);
                p.execute();
                c.close();
                System.out.println("insert done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_insertCustomerActionPerformed

    private void updateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerActionPerformed
        var id = customerID.getText();
        var name = customerName.getText();
        var roomID = CusRoomNumber.getText();
        if (id.length() != 0) {
            int ID = Integer.parseInt(id);
            int RoomNumber;
            try {
                RoomNumber = Integer.parseInt(roomID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("UPDATE `customer` SET `name` = ? ,`roomNumber`= ? WHERE `customer`.`ID` = ?");
                p.setString(1, name);
                p.setInt(2, RoomNumber);
                p.setInt(3, ID);
                p.execute();
                c.close();
                System.out.println("update done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateCustomerActionPerformed

    private void removeCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerActionPerformed
        var id = customerID.getText();
        //var name = customerName.getText();
        if (id.length() != 0) {
            int ID = Integer.parseInt(id);
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("DELETE FROM `customer` WHERE `customer`.`ID` = ?");
                p.setInt(1, ID);
                //p.setString(1, name);
                p.execute();
                c.close();
                System.out.println("remove done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removeCustomerActionPerformed

    private void insertEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertEmployeeActionPerformed
        var id = empID.getText();
        var name = empName.getText();
        var salary = empSalary.getText();
        var hotelID = empHotelID.getText();
        if (id.length() != 0 && salary.length() != 0 && hotelID.length() != 0) {
            int ID;
            double Salary;
            int HotelID;
            try {
                ID = Integer.parseInt(id);
                Salary = Double.parseDouble(salary);
                HotelID = Integer.parseInt(hotelID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("INSERT INTO `employee`(`ID`, `name`, `salary`, `HotelID`) VALUES (?,?,?,?)");
                p.setInt(1, ID);
                p.setString(2, name);
                p.setDouble(3, Salary);
                p.setInt(4, HotelID);
                p.execute();
                c.close();
                System.out.println("insert done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_insertEmployeeActionPerformed

    private void updateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeActionPerformed
        var id = empID.getText();
        var name = empName.getText();
        var salary = empSalary.getText();
        var hotelID = empHotelID.getText();
        if (id.length() != 0 && salary.length() != 0 && hotelID.length() != 0) {
            int ID;
            double Salary;
            int HotelID;
            try {
                ID = Integer.parseInt(id);
                Salary = Double.parseDouble(salary);
                HotelID = Integer.parseInt(hotelID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("UPDATE `employee` SET `name` = ?, `salary` = ?, `HotelID` = ? WHERE `employee`.`ID` = ?");
                p.setString(1, name);
                p.setDouble(2, Salary);
                p.setInt(3, HotelID);
                p.setInt(4, ID);
                p.execute();
                c.close();
                System.out.println("update done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateEmployeeActionPerformed

    private void removeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeActionPerformed
        var id = empID.getText();
        ;
        if (id.length() != 0) {
            int ID;
            try {
                ID = Integer.parseInt(id);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("DELETE FROM `employee` WHERE `employee`.`ID` = ?");
                p.setInt(1, ID);
                p.execute();
                c.close();
                System.out.println("remove done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removeEmployeeActionPerformed
    
    private void insertRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertRoomActionPerformed
        var number = RoomNumber.getText();
        var price = roomPrice.getText();
        var type = roomType.getText();
        var hotelID = roomHotelId.getText();
        if (number.length() != 0) {
            int Number;
            double Price;
            int HotelID;
            try {
                Number = Integer.parseInt(number);
                Price = Double.parseDouble(price);
                HotelID = Integer.parseInt(hotelID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("INSERT INTO `room`(`number`, `price`, `type`, `HotelID`) VALUES (?,?,?,?)");
                p.setInt(1, Number);
                p.setDouble(2, Price);
                p.setString(3, type);
                p.setInt(4, HotelID);
                p.execute();
                c.close();
                System.out.println("insert done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_insertRoomActionPerformed

    private void removeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRoomActionPerformed
        var number = RoomNumber.getText();
        if (number.length() != 0) {
            int Number;
            try {
                Number = Integer.parseInt(number);

                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("DELETE FROM `room` WHERE `room`.`number` = ?");
                p.setInt(1, Number);
                p.execute();
                c.close();
                System.out.println("remove done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removeRoomActionPerformed

    private void removeHotel1ActionPerformed(java.awt.event.ActionEvent evt) {
        var x = insertHotelID1.getText();
        if (x.length() != 0) {
            int ID = Integer.parseInt(x);
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("DELETE FROM `hotel` WHERE `hotel`.`ID` = ?");
                p.setInt(1, ID);
                p.execute();
                c.close();
                System.out.println("remove done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void updateHotel1ActionPerformed(java.awt.event.ActionEvent evt) {

        var x = insertHotelID1.getText();
        var name = insertHotelName1.getText();
        var location = locHotelInsert1.getText();

        if (x.length() != 0) {
            int ID = Integer.parseInt(x);
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("UPDATE `hotel` SET `name`=?,`location`=? WHERE `hotel`.`ID` = ?");
                //p.setInt(1,ID);
                p.setString(1, name);
                p.setString(2, location);
                p.setInt(3, ID);
                p.execute();
                c.close();
                System.out.println("update done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    private void insertHotelName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertHotelName1ActionPerformed

    }//GEN-LAST:event_insertHotelName1ActionPerformed

    private void insertHotelID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertHotelID1ActionPerformed

    }//GEN-LAST:event_insertHotelID1ActionPerformed

    private void locHotelInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locHotelInsert1ActionPerformed
    }//GEN-LAST:event_locHotelInsert1ActionPerformed

    private void instertHotel2ActionPerformed(java.awt.event.ActionEvent evt) {
        var id = insertHotelID1.getText();
        var name = insertHotelName1.getText();
        var location = locHotelInsert1.getText();
        if (id.length() != 0) {
            int ID = Integer.parseInt(id);
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("INSERT INTO `hotel`(`ID`, `name`, `location`) VALUES (?,?,?)");
                p.setInt(1, ID);
                p.setString(2, name);
                p.setString(3, location);
                p.execute();
                c.close();
                System.out.println("insert done");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    //here
    private void updateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRoomActionPerformed
        var number = RoomNumber.getText();
        var price = roomPrice.getText();
        var type = roomType.getText();
        var hotelID = roomHotelId.getText();
        if (number.length() != 0) {
            int Number;
            double Price;
            int HotelID;
            try {
                Number = Integer.parseInt(number);
                Price = Double.parseDouble(price);
                HotelID = Integer.parseInt(hotelID);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("UPDATE `room` SET `price`=?,`type`=?,`HotelID`=? WHERE `room`.`number` = ?");
                p.setDouble(1, Price);
                p.setString(2, type);
                p.setInt(3, HotelID);
                p.setInt(4, Number);
                p.execute();
                c.close();
                System.out.println("update done");
            } catch (SQLException e) {
                var f = new Frame();
                f.addWindowListener((WindowListener) this);
                f.setSize(300,300);
                f.setLayout(null);
                f.setVisible(true);
                JOptionPane.showConfirmDialog(f,e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                var f = new Frame();
                f.addWindowListener((WindowListener) this);
                f.setSize(300,300);
                f.setLayout(null);
                f.setVisible(true);
                JOptionPane.showConfirmDialog(f,e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateRoomActionPerformed

    private void roomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomPriceActionPerformed
    }//GEN-LAST:event_roomPriceActionPerformed

    private void RoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumberActionPerformed
    }//GEN-LAST:event_RoomNumberActionPerformed

    private void roomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeActionPerformed
    }//GEN-LAST:event_roomTypeActionPerformed

    private void empIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDActionPerformed
    }//GEN-LAST:event_empIDActionPerformed

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
    }//GEN-LAST:event_empNameActionPerformed

    private void empSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSalaryActionPerformed
    }//GEN-LAST:event_empSalaryActionPerformed

    private void customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIDActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
    }//GEN-LAST:event_customerNameActionPerformed

    private void roleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleNameActionPerformed

    private void roleRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleRankActionPerformed

    private void empHotelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empHotelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empHotelIDActionPerformed

    private void roomHotelIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomHotelIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomHotelIdActionPerformed

    private void removeWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeWorkActionPerformed
        var id = workEmpID.getText();
        var name = workRoleName.getText();
        if (id.length() != 0) {
            int ID;
            try {
                ID = Integer.parseInt(id);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("DELETE FROM `working as` WHERE (`working as`.`EmployeeID` = ? and `working as`.`RoleName` = ?) ");
                p.setInt(1, ID);
                p.setString(2, name);
                p.execute();
                c.close();
                System.out.println("remove done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removeWorkActionPerformed

    private void updateWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWorkActionPerformed
        var id = workEmpID.getText();
        var name = workRoleName.getText();
        if (id.length() != 0) {
            int ID;
            try {
                ID = Integer.parseInt(id);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("UPDATE `working as` SET `RoleName`= ? WHERE `working as`.`EmployeeID` = ?");
                p.setString(1, name);
                p.setInt(2, ID);
                p.execute();
                c.close();
                System.out.println("update done");
            } catch (SQLException e) {
                e.printStackTrace();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateWorkActionPerformed

    private void insertWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertWorkActionPerformed
        var id = workEmpID.getText();
        var name = workRoleName.getText();
        if (id.length() != 0) {
            int ID;
            try {
                ID = Integer.parseInt(id);
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/manage_hotel", "root", "ahmad");
                System.out.println("connection done");
                PreparedStatement p = c.prepareStatement("INSERT INTO `working as`(`EmployeeID`, `RoleName`) VALUES (?,?)");
                p.setInt(1, ID);
                p.setString(2, name);
                p.execute();
                c.close();
                System.out.println("insert done");
            } catch (SQLException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_insertWorkActionPerformed

    private void workEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workEmpIDActionPerformed

    private void workRoleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workRoleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workRoleNameActionPerformed

    private void CusRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusRoomNumberActionPerformed

    private void displayHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayHotelActionPerformed
        // TODO add your handling code here:
        t.displayhotel();
        t.setVisible(true);
    }//GEN-LAST:event_displayHotelActionPerformed

    private void displayRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRoomActionPerformed
        // TODO add your handling code here:
        t.displayRoom();
        t.setVisible(true);
    }//GEN-LAST:event_displayRoomActionPerformed

    private void displayRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRoom1ActionPerformed
        // TODO add your handling code here:
        t.displayeEmp();
        t.setVisible(true);
    }//GEN-LAST:event_displayRoom1ActionPerformed

    private void displayCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCusActionPerformed
        // TODO add your handling code here:
        t.displayeCus();
        t.setVisible(true);
    }//GEN-LAST:event_displayCusActionPerformed

    private void displayRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRoleActionPerformed
        // TODO add your handling code here:
        t.displayeRole();
        t.setVisible(true);
    }//GEN-LAST:event_displayRoleActionPerformed

    private void displayWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayWorkActionPerformed
        // TODO add your handling code here:
        t.displayeWork();
        t.setVisible(true);
    }//GEN-LAST:event_displayWorkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_Mangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_Mangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_Mangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_Mangment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_Mangment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CIDinsert;
    private javax.swing.JLabel CNameinsert;
    private javax.swing.JTextField CusRoomNumber;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JLabel EmpIDinsert;
    private javax.swing.JLabel EmpIDinsert1;
    private javax.swing.JLabel EmpNameinsert;
    private javax.swing.JLabel EmpSalaryInsert;
    private javax.swing.JPanel EmployeePanel;
    private javax.swing.JLabel HotelIDInsert1;
    private javax.swing.JLabel HotelIDInsert3;
    private javax.swing.JLabel HotelIDInsert5;
    private javax.swing.JLabel HotelNameInsert1;
    private javax.swing.JLabel HotelNameInsert3;
    private javax.swing.JPanel HotelPanel;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JTextField RoomNumber;
    private javax.swing.JPanel RoomPanel;
    private javax.swing.JPanel Workpanel;
    private javax.swing.JTextField customerID;
    private javax.swing.JTextField customerName;
    private javax.swing.JButton displayCus;
    private javax.swing.JButton displayHotel;
    private javax.swing.JButton displayRole;
    private javax.swing.JButton displayRoom;
    private javax.swing.JButton displayRoom1;
    private javax.swing.JButton displayWork;
    private javax.swing.JTextField empHotelID;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empSalary;
    private javax.swing.JLabel hotelLocInsert1;
    private javax.swing.JLabel hotelLocInsert3;
    private javax.swing.JButton insertCustomer;
    private javax.swing.JButton insertEmployee;
    private javax.swing.JTextField insertHotelID1;
    private javax.swing.JTextField insertHotelName1;
    private javax.swing.JButton insertRole;
    private javax.swing.JButton insertRoom;
    private javax.swing.JButton insertWork;
    private javax.swing.JButton instertHotel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField locHotelInsert1;
    private javax.swing.JButton removeCustomer;
    private javax.swing.JButton removeEmployee;
    private javax.swing.JButton removeHotel1;
    private javax.swing.JButton removeRole;
    private javax.swing.JButton removeRoom;
    private javax.swing.JButton removeWork;
    private javax.swing.JTextField roleName;
    private javax.swing.JLabel roleNameinsert;
    private javax.swing.JLabel roleNameinsert1;
    private javax.swing.JTextField roleRank;
    private javax.swing.JLabel roleRankinsert;
    private javax.swing.JLabel roleRankinsert1;
    private javax.swing.JTextField roomHotelId;
    private javax.swing.JTextField roomPrice;
    private javax.swing.JTextField roomType;
    private javax.swing.JLabel roomnumberinsert;
    private javax.swing.JButton updateCustomer;
    private javax.swing.JButton updateEmployee;
    private javax.swing.JButton updateHotel1;
    private javax.swing.JButton updateRole;
    private javax.swing.JButton updateRoom;
    private javax.swing.JButton updateWork;
    private javax.swing.JTextField workEmpID;
    private javax.swing.JTextField workRoleName;
    // End of variables declaration//GEN-END:variables
}
